
# Day 7 -Aggregate Functions in NumPy

In [1]:
import numpy as np
arr = np.zeros((10,2)) # 2D array of 10 rows and 2 columns filled with zeros
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [2]:
arr = np.zeros((2,10,2)) # 3D array of 2 blocks, each containing a 10x2 array filled with zeros
print(arr)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [3]:
arr = np.ones((10,2)) # 2D array of 10 rows and 2 columns filled with ones
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
arr = np.ones((2,10,2)) # 3D array of 2 blocks, each containing a 10x2 array filled with ones
print(arr)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [5]:
arr = np.full((2,3), 7) # 2D array of 2 rows and 3 columns filled with the value 7
print(arr)

[[7 7 7]
 [7 7 7]]


In [6]:
arr=np.eye(2) # 2D identity matrix of size 2x2
print(arr,"\n")

arr=np.eye(3) # 3D identity matrix of size 3x3
print(arr)

[[1. 0.]
 [0. 1.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
arr = np.empty((3,2,4)) # 2D array of 2 rows and 4 columns with uninitialized values
print(arr)

[[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.60219578e-306]
  [7.56587584e-307 1.37961302e-306 1.05699242e-307 8.01097889e-307]]

 [[1.78020169e-306 7.56601165e-307 1.02359984e-306 1.33510679e-306]
  [2.22522597e-306 8.01097889e-307 1.42417629e-306 8.45593934e-307]]

 [[6.89805151e-307 8.45606157e-307 1.78019082e-306 1.29061414e-306]
  [8.45559303e-307 1.06811422e-306 1.05694828e-307 1.42410974e-306]]]


In [8]:
arr = np.arange(0,100,2) # 1D array with values from 0 to 9 # starts at 0, ends before 100, with a step of 2
print(arr)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [9]:
arr = np.arange(0,100,1) # 1D array with values from 0 to 9
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [10]:
arr = np.arange(0,100,15) # 1D array with values from 0 to 9
print(arr)

[ 0 15 30 45 60 75 90]


In [11]:
arr = np.linspace(0,100,5) # start at 0, end at 100, with 5 (count number) evenly spaced values
print(arr)

[  0.  25.  50.  75. 100.]


In [12]:
print(np.mean(arr)) # mean of the array 
print(np.median(arr)) # median of the array
print(np.std(arr)) # standard deviation of the array
print(np.var(arr)) # variance of the array
print(np.min(arr)) # minimum value in the array
print(np.sum(arr)) # sum of all elements in the array
print(np.max(arr)) # maximum value in the array
print(np.argmin(arr)) # index of the minimum value in the array
print(np.argmax(arr)) # index of the maximum value in the array

50.0
50.0
35.35533905932738
1250.0
0.0
250.0
100.0
0
4


In [13]:
arr=np.array([
              [1,2,3],
              [4,5,6]
            ]) # 2D array with specified values 
print(np.argmax(arr)) # index of the maximum value in the array (returns the index in the flattened array)
print(np.argmin(arr)) # index of the minimum value in the array (returns the index in the flattened array)
print(np.sum(arr,axis=0)) # sum of all elements in the array along axis 0 sums the columns
print(np.sum(arr,axis=1)) # sum of all elements in the array along axis 1 sums the rows

5
0
[5 7 9]
[ 6 15]



# Day 8  Filtering in NumPy, Where


In [14]:
mark = np.array([50,100,65,45,76])
print(mark)

[ 50 100  65  45  76]


In [15]:
print(mark[mark>50])

[100  65  76]


In [16]:
print(mark>50)

[False  True  True False  True]


In [18]:
pass_mark = mark[mark>=50]
print(pass_mark)

[ 50 100  65  76]


In [20]:
even = mark[mark%2==0]
print(even)

[ 50 100  76]


In [24]:
ark = mark[(mark >= 50) & (mark <= 70)]
print(ark)

[50 65]


In [27]:
ak = mark[(mark >= 50) | (mark%2==0)]
print(ak)

[ 50 100  65  76]


In [28]:
# multi dimensional array filtering
arr = np.array([
              [1,2,3],
              [4,5,6]
            ]) # 2D array with specified values

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
even = arr[arr%2==0] #this using flattened array to filter even numbers
print(even)

[2 4 6]


In [ ]:
even = np.where(arr%2==0,arr,0) # this using np.where to filter even numbers and replace odd numbers with 0 and shape of the original array is preserved
print(even)

[[0 2 0]
 [4 0 6]]
