# Day 5 - Arithmetic Operators, Vector & Scalar

This section covers the use of arithmetic operators with vectors and scalars in Python. Arithmetic operators such as `+`, `-`, `*`, `/`, and `**` can be applied to both scalars and vectors (using libraries like NumPy) to perform element-wise operations or scalar multiplication/division. Understanding these operations is fundamental for numerical computing and data analysis workflows.

In [1]:
import numpy as np

In [2]:
arr= np.array([25,24,5,2])
print(arr)

[25 24  5  2]


```markdown
The following examples demonstrate element-wise arithmetic operations on a NumPy array `arr`:

```python
print(arr + 1)   # Adds 1 to each element of 'arr'
print(arr - 5)   # Subtracts 5 from each element of 'arr'
print(arr * 5)   # Multiplies each element of 'arr' by 5
print(arr / 5)   # Divides each element of 'arr' by 5
print(arr ** 5)  # Raises each element of 'arr' to the power of 5
```

Each operation is performed element-wise, meaning the operation is applied to every element in the array individually.
```

In [3]:
print(arr+1) # This line adds 1 to each element of the NumPy array 'arr'. The operation is performed element-wise, meaning that 1 will be added to each individual element in the array. The output will show the resulting array after the addition, where each element is increased by 1.
print(arr-5) # This line subtracts 5 from each element of the NumPy array 'arr'. The operation is performed element-wise, meaning that 5 will be subtracted from each individual element in the array. The output will show the resulting array after the subtraction, where each element is decreased by 5. For example.
print(arr*5) # This line multiplies each element of the NumPy array 'arr' by 5. The operation is performed element-wise, meaning that each individual element in the array will be multiplied by 5. The output will show the resulting array after the multiplication, where each element is increased by a factor of 5.
print(arr/5) # This line divides each element of the NumPy array 'arr' by 5. The operation is performed element-wise, meaning that each individual element in the array will be divided by 5. The output will show the resulting array after the division, where each element is decreased by a factor of 5. For example.
print(arr**5) # This line raises each element of the NumPy array 'arr' to the power of 5. The operation is performed element-wise, meaning that each individual element in the array will be raised to the power of 5. The output will show the resulting array after the exponentiation, where each element is increased by a factor of itself raised to the power of 5. For example.

[26 25  6  3]
[20 19  0 -3]
[125 120  25  10]
[5.  4.8 1.  0.4]
[9765625 7962624    3125      32]


In [4]:
brr= np.sqrt(arr) 
print(np.round(brr)) # This line calculates the square root of each element in the NumPy array 'arr' using the 'sqrt' function from the NumPy library. The operation is performed element-wise, meaning that the square root will be calculated for each individual element in the array. The output will show the resulting array after the square root calculation, where each element is transformed to its square root value. For example, if the original array is [25, 24, 5, 2], the output will be [5.0, 4.89897949, 2.23606798, 1.41421356].

[5. 5. 2. 1.]


In [5]:
print(np.floor(brr)) # This line calculates the floor of each element in the NumPy array 'brr' using the 'floor' function from the NumPy library. The operation is performed element-wise, meaning that the floor will be calculated for each individual element in the array. The output will show the resulting array after the floor calculation, where each element is transformed to the largest integer less than or equal to its value. For example, if 'brr' contains [5.0, 4.89897949, 2.23606798, 1.41421356], the output will be [5.0, 4.0, 2.0, 1.0].

[5. 4. 2. 1.]


In [6]:
print(np.ceil(brr)) # This line calculates the ceiling of each element in the NumPy array 'brr' using the 'ceil' function from the NumPy library. The operation is performed element-wise, meaning that the ceiling will be calculated for each individual element in the array. The output will show the resulting array after the ceiling calculation, where each element is transformed to the smallest integer greater than or equal to its value. For example, if 'brr' contains [5.0, 4.89897949, 2.23606798, 1.41421356], the output will be [5.0, 5.0, 3.0, 2.0].

[5. 5. 3. 2.]


In [7]:
brr= np.array([1,2,3,4])
print(arr+brr) # This line adds the NumPy array 'brr' to the NumPy array 'arr' element-wise. The operation is performed by adding each corresponding element from 'arr' and 'brr'. The output will show the resulting array after the addition, where each element is the sum of the corresponding elements from 'arr' and 'brr'. For example, if 'arr' is [25, 24, 5, 2] and 'brr' is [1, 2, 3, 4], the output will be [26, 26, 8, 6].
print(arr-brr) # This line subtracts the NumPy array 'brr' from the NumPy array 'arr' element-wise. The operation is performed by subtracting each corresponding element of 'brr' from 'arr'. The output will show the resulting array after the subtraction, where each element is the difference between the corresponding elements from 'arr' and 'brr'. For example, if 'arr' is [25, 24, 5, 2] and 'brr' is [1, 2, 3, 4], the output will be [24, 22, 2, -2].
print(arr*brr) # This line multiplies the NumPy array 'arr' by the  NumPy array 'brr' element-wise. The operation is performed by multiplying each corresponding element from 'arr' and 'brr'. The output will show the resulting array after the multiplication, where each element is the product of the corresponding elements from 'arr' and 'brr'. For example, if 'arr' is [25, 24, 5, 2] and 'brr' is [1, 2, 3, 4], the output will be [25, 48, 15, 8].
print(arr/brr) # This line divides the NumPy array 'arr' by the NumPy array 'brr' element-wise. The operation is performed by dividing each corresponding element of 'arr' by the corresponding element of 'brr'. The output will show the resulting array after the division, where each element is the quotient of the corresponding elements from 'arr' and 'brr'. For example, if 'arr' is [25, 24, 5, 2] and 'brr' is [1, 2, 3, 4], the output will be [25.0, 12.0, 1.66666667, 0.5].
print(arr**brr) # This line raises each element of the NumPy array 'arr to the power of the corresponding element in the NumPy array 'brr' element-wise. The operation is performed by taking each element of 'arr' and raising it to the power of the corresponding element in 'brr'. The output will show the resulting array after the exponentiation, where each element is the result of raising the corresponding element from 'arr' to the power of the corresponding element from 'brr'. For example, if 'arr' is [25, 24, 5, 2] and 'brr' is [1, 2, 3, 4], the output will be [25.0, 576.0, 125.0, 16.0].  


[26 26  8  6]
[24 22  2 -2]
[25 48 15  8]
[25.         12.          1.66666667  0.5       ]
[ 25 576 125  16]


The code below demonstrates how to access and print the value of π (pi) using NumPy. The `np.pi` constant provides the mathematical value of π, which is useful for various mathematical and scientific computations.

```python
print(np.pi)
```

**Output:**
```
3.141592653589793
```

In [8]:
print(np.pi) # This line prints the value of π (pi) from the NumPy library. The 'pi' constant in NumPy represents the mathematical constant π, which is approximately equal to 3.141592653589793. The output will show the value of π when this line is executed.

3.141592653589793


In [9]:
print(2 * np.pi*brr)

[ 6.28318531 12.56637061 18.84955592 25.13274123]


In [10]:
age = np.array([25, 24, 50, 18,6,17])
print(age<18) # This line compares each element of the NumPy array 'age' to the value 18 and returns a boolean array. The operation is performed element-wise, meaning that each element in 'age' will be compared to 18, and the output will show 'True' for elements that are less than 18 and 'False' for elements that are greater than or equal to 18. For example, if 'age' is [25, 24, 50, 18, 6, 17], the output will be [False, False, False, False, True, True].
print(age==18) # This line compares each element of the NumPy array 'age' to the value 18 and returns a boolean array. The operation is performed element-wise, meaning that each element in 'age' will be compared to 18, and the output will show 'True' for elements that are equal to 18 and 'False' for elements that are not equal to 18. For example, if 'age' is [25, 24, 50, 18, 6, 17], the output will be [False, False, False, True, False, False].
print(age>=18) # This line compares each element of the NumPy array 'age' to the value 18 and returns a boolean array. The operation is performed element-wise, meaning that each element in 'age' will be compared to 18, and the output will show 'True' for elements that are greater than or equal to 18 and 'False' for elements that are less than 18. For example, if 'age' is [25, 24, 50, 18, 6, 17], the output will be [True, True, True, True, False, False].

[False False False False  True  True]
[False False False  True False False]
[ True  True  True  True False False]


In [11]:
age[age<18]=18 # This line modifies the NumPy array 'age' by setting all elements that are less than 18 to the value 18. The operation is performed element-wise, meaning that each element in 'age' will be checked against the condition (age < 18), and if the condition is true for an element, that element will be updated to 18. The output will show the modified array after this operation, where all values that were originally less than 18 have been replaced with 18. For example, if 'age' is [25, 24, 50, 18, 6, 17], after this line is executed, 'age' will become [25, 24, 50, 18, 18, 18].
print(age)

[25 24 50 18 18 18]


In [12]:
age[age>50]=15
print(age)

[25 24 50 18 18 18]


# Day 6 Broadcasting 

In [13]:
import numpy as np
arr =np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

brr= np.array([[1,2,3]]) 
"""
1 1 1
2 2 2
3 3 3
"""
print(arr.shape) # This line prints the shape of the NumPy array 'arr'. The 'shape' attribute of a NumPy array returns a tuple representing the dimensions of the array. In this case, since 'arr' is a 2D array with 3 rows and 3 columns, the output will be (3, 3), indicating that 'arr' has 3 rows and 3 columns.
print(brr.shape) # This line prints the shape of the NumPy array 'brr'. The 'shape' attribute of a NumPy array returns a tuple representing the dimensions of the array. In this case, since 'brr' is a 2D array with 1 row and 3 columns, the output will be (1, 3), indicating that 'brr' has 1 row and 3 columns.

(3, 3)
(1, 3)


In [14]:
print(arr*brr)
 # This line multiplies the NumPy array 'arr' by the NumPy array 'brr' element-wise. 
 # The operation is performed by multiplying each corresponding element from 'arr' and 'brr'. However, since 'arr' has a shape of (3, 3) and 'brr' has a shape of (1, 3), NumPy will automatically broadcast 'brr' across the rows of 'arr'. 
 # This means that the single row of 'brr' will be repeated for each row of 'arr', allowing for element-wise multiplication to occur.
 # The output will show the resulting array after the multiplication, where each element is the product of the corresponding elements from 'arr' and 'brr'.
 # For example, if 'arr' is [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and 'brr' is [[1, 2, 3]], the output will be [[1*1, 2*2, 3*3], [4*1, 5*2, 6*3], [7*1, 8*2, 9*3]], which simplifies to [[1, 4, 9], [4, 10, 18], [7, 16, 27]].

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]


In [15]:
print(arr+brr) # This line adds the NumPy array 'arr' to the NumPy array 'brr' element-wise.
# Similar to the previous multiplication operation, since 'arr' has a shape of (3, 3) and 'brr' has a shape of (1, 3), NumPy will automatically broadcast 'brr' across the rows of 'arr'.
#  This means that the single row of 'brr' will be repeated for each row of 'arr', allowing for element-wise addition to occur. The output will show the resulting array after the addition, where each element is the sum of the corresponding elements from 'arr' and 'brr'. 
# For example, if 'arr' is [[1, 2, 3], [4, 5, 6], [7, 8, 9]] and 'brr' is [[1, 2, 3]], the output will be [[1+1, 2+2, 3+3], [4+1, 5+2, 6+3], [7+1, 8+2, 9+3]], which simplifies to [[2, 4, 6], [5, 7, 9], [8, 10, 12]]

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
