In [25]:
import numpy as np
rng= np.random.default_rng(seed=23) # this is how to create a random number generator with a specific seed value, 
#which ensures that the same sequence of random numbers is generated each time the code is run. seed value can be any integer, and it is used to initialize the random number generator's internal state. By using the same seed value, you can reproduce the same sequence of random numbers, which can be useful for debugging or for sharing code with others.
mark = rng.integers(1,31)
print(mark)

2


In [26]:
print(rng.integers(low=1, high=31)) # this is another way to generate random integer between 1 and 30

21


In [27]:
print(rng.integers(low=1, high=31,size=10)) # this is another way to generate 10 random integer between 1 and 30

[13 20  8  4 19  4  4 20 20 26]


In [28]:
print(rng.integers(low=1, high=31, size=(3,4))) # this is another way to generate 3x4 random integer between 1 and 30

[[14  7  7  7]
 [ 4 22 23 15]
 [21 13 22 11]]


In [29]:
print(np.random.uniform(low=100, high=1,size=5)) # this is how to generate 5 random float numbers between 1 and 100

[53.78373319 31.94118079 12.79496971 68.83019513 31.18219193]


In [30]:
arr = np.array(["king","queen","prince","princess","knight","bishop","rook","pawn"]) # this is how to create a 1D array of strings with specified values
rng.shuffle(arr) # this is how to shuffle the elements of the array in place, which means that the original array is modified and the order of the elements is changed randomly. The shuffle function uses a random number generator to determine the new order of the elements, and it does not return a new array. After calling shuffle, the original array will have its elements rearranged in a random order.
print(arr)

['prince' 'princess' 'knight' 'king' 'pawn' 'queen' 'bishop' 'rook']


In [31]:
print(rng.choice(arr)) # this is how to randomly select a single element from the array, which means that one of the elements in the array will be chosen at random and returned as the output. The choice function uses a random number generator to determine which element to select, and it does not modify the original array. Each time you call choice, you may get a different result, depending on the random selection process.

knight


## Day 10 Linear Algebra & File Handling

In [32]:
import os
print(os.getcwd()) # this is how to get the current working directory, which is the directory in which the Python script or notebook is being executed. The getcwd function returns a string representing the current working directory, which can be useful for file operations or for understanding the context of your code.

d:\leanring\aids\numpy


In [33]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10]) # this is how to create a 1D array of integers with specified values
np.save("data.npy", arr) # this is how to save the array to a file named "data.npy" in the current working directory. The save function takes the filename and the array as arguments, and it saves the array in a binary format that can be loaded later using the load function.

In [34]:
read=np.load("data.npy") # this is how to load the array from the file named "data.npy" in the current working directory. The load function takes the filename as an argument and returns the array that was saved in that file. After loading, you can use the read variable to access the contents of the array.
print(read)

[ 1  2  3  4  5  6  7  8  9 10]


In [35]:
brr = np.array([11,12,13,14,15,16,17,18,19,20]) # this is how to create another 1D array of integers with specified values
np.savez("data.npz", arr, brr) # this is how to save both arrays in a single file named "data.npz" in the current working directory. The savez function takes the filename and the arrays as keyword arguments, where the keys (a and b) are used to identify the arrays when loading them later.   


In [36]:
read = np.load("data.npz") # this is how to load the array from the file named "data.npz" in the current working directory. The load function takes the filename as an argument and returns the array that was saved in that file. After loading, you can use the read_arr variable to access the contents of the array that was saved.
print(read)

NpzFile 'data.npz' with keys: arr_0, arr_1


In [37]:
print(read["arr_0"]) # this is how to access the first array (arr) that was saved in the "data.npz" file.
print(read["arr_1"]) # this is how to access the second array (brr) that was saved in the "data.npz" file.

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


# Linear Algebra

In [40]:
a =([
    [1,2],
    [3,4]
])
b =([
    [5,6],
    [7,8]
])

In [41]:
print(np.matmul(a,b)) # this is how to perform matrix multiplication between two 2D arrays (matrices) a and b. The matmul function takes two arrays as input and returns the result of their matrix multiplication. In this case, the resulting array will be a 2x2 matrix that is the product of the two input matrices a and b.

[[19 22]
 [43 50]]


In [46]:
arr = np.array([1,2,3])
brr = np.array([4,2,3])
print(np.dot(arr, brr))

17


In [51]:
b=np.array([
    [5,6],
    [7,8]
])
print(b.T) # this is how to transpose a 2D array (matrix) b. The T attribute returns the transposed version of the array, which means that the rows and columns are swapped. In this case, the resulting array will have its first row as [5,7] and its second row as [6,8], effectively flipping the original matrix along its diagonal.

[[5 7]
 [6 8]]


In [52]:
print(np.linalg.det(b)) # this is how to calculate the determinant of a 2D array (matrix) b. The linalg.det function takes a square matrix as input and returns its determinant, which is a scalar value that can be used to determine whether the matrix is invertible or not. If the determinant is zero, the matrix is singular and does not have an inverse. If the determinant is non-zero, the matrix is invertible and has an inverse. In this case, the determinant of matrix b will be calculated and printed as the output.

-1.999999999999999
