# Introduction to NumPy

NumPy (Numerical Python) is a fundamental library for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

## Key Features

- **N-dimensional Array Object (`ndarray`)**: Core data structure for storing elements of the same type.
- **Broadcasting**: Perform arithmetic operations on arrays of different shapes.
- **Vectorization**: Apply operations to entire arrays without explicit loops, leading to faster code.
- **Mathematical Functions**: Includes functions for linear algebra, statistics, Fourier analysis, and more.
- **Integration with Other Libraries**: Forms the foundation for libraries like Pandas, SciPy, and scikit-learn.

## Why Use NumPy?

- **Performance**: NumPy operations are implemented in C, making them much faster than native Python lists.
- **Convenience**: Simplifies code for mathematical and statistical operations.
- **Memory Efficiency**: Arrays consume less memory compared to Python lists.

## Basic Concepts

### 1. Array Creation

```python
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
```

### 2. Array Attributes

- `shape`: Dimensions of the array
- `dtype`: Data type of elements
- `ndim`: Number of dimensions

### 3. Array Operations

- **Element-wise arithmetic**: `arr1 + arr2`, `arr1 * arr2`
- **Aggregation**: `np.sum(arr)`, `np.mean(arr)`
- **Reshaping**: `arr.reshape((2, 3))`

### 4. Data Types

NumPy supports various data types, such as `int8`, `int16`, `float32`, `bool_`, and `str_`. You can specify the data type when creating an array.

### 5. Slicing and Indexing

NumPy arrays support advanced slicing and indexing, allowing you to access and modify subsets of data efficiently.

## Example

```python
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)      # (2, 3)
print(a[0, 1])      # 2
print(a.sum(axis=0)) # [5 7 9]
```

## Summary

NumPy is essential for data analysis, machine learning, and scientific computing in Python. Its efficient array operations and mathematical functions make it a powerful tool for handling numerical data.

# Day 1: NumPy

In this notebook, we explore basic NumPy operations and array manipulations.  
Key variables:
- `arr`: a 3x3 NumPy array  
- `array`: a 1D NumPy array with repeated values

We will demonstrate array creation, type checking, and basic arithmetic operations.

In [1]:
import numpy as np  # Import NumPy library
print(np.__version__)  # Print the version of NumPy installed

2.3.5


In [2]:

array = [1, 2, 3, 4, 5] # This is a 1D array with 5 elements
print(array)

[1, 2, 3, 4, 5]


In [3]:
print(type(array)) # The type of the variable 'array' is <class 'list'> which means it is a Python list, not a NumPy array

<class 'list'>


In [4]:
array=array*2 # This operation multiplies each element of the list 'array' by 2, resulting in a new list [2, 4, 6, 8, 10]
print(array)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [5]:
array=np.array(array) # This converts the Python list 'array' into a NumPy array, allowing for more efficient numerical operations and access to NumPy's functionality
print(array)
print(type(array))

[1 2 3 4 5 1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
array=array*2 # This operation multiplies each element of the list 'array' by 2, resulting in a new list [2, 4, 6, 8, 10]
print(array)

[ 2  4  6  8 10  2  4  6  8 10]


In [7]:
brray=np.array([1,23,4,5,6,7,8,9,0]) # This creates a NumPy array called 'brray' with the specified list of integers as its elements
print(brray)

[ 1 23  4  5  6  7  8  9  0]


In [8]:
print(array + brray) # This operation adds the corresponding elements of the two arrays 'array' and 'brray' together, resulting in a new array where each element is the sum of the corresponding elements from the original arrays. The output will be [ 3 27 11 13 17 19 21 23 15] 


ValueError: operands could not be broadcast together with shapes (10,) (9,) 

# Reason
NumPy can only add arrays if they have the same length.  
The error happens because `array` and `brray` have different lengths.  
To fix this, make sure both arrays have the same number of elements before adding them.

In [ ]:
brray=np.array([1,2,3,4,5,6,7,8,9,0]) 
print(array + brray)


## Day 2: Data Types in NumPy

- **dtype**: Specifies the data type of elements in a NumPy array.
- **astype**: Used to convert the array to a different data type.
- **int8, int16, int32, int64**: Integer data types with varying byte sizes.
- **float16, float32, float64**: Floating-point data types with varying precision.
- **bool_**: Boolean data type (`True` or `False`).
- **str_**: String data type for Unicode text.

Example:
```python
arr.astype(np.float32)  # Convert array to float32
arr.astype(np.bool_)    # Convert array to boolean
```


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))


In [ ]:
print(arr)
print(arr.dtype) # This line prints the data type of the elements in the NumPy array 'arr'. In this case, it will output 'int64' or 'int32' depending on the system, indicating that the elements are integers.


In [ ]:
arr = np.array([1, 2, 3, 4, 5], dtype=int8) 

# Reason
The error occurs because `np` (NumPy) is not defined in the current cell.  
To fix this, first import NumPy using `import numpy as np`.  
Then, use `np.int8` for the data type like this:  
import numpy as np  
arr = np.array([1, 2, 3, 4, 5], dtype=np.int8)  

Always write `np.int8` (not just `int8`) to avoid errors.


# int 8,int 16,int 32,int 64
 example
        2^8 = 256 ⇒ -128 to 127 (for int8)  # include 0

        2^16 = 65,536 ⇒ -32,768 to 32,767 (for int16)   # include 0

        2^32 = 4,294,967,296 ⇒ -2,147,483,648 to 2,147,483,647 (for int32)   # include 0
        
        2^64 = 18,446,744,073,709,551,616 ⇒ -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807 (for int64)  # include 0


In [ ]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.int8) # This line creates a NumPy array with the specified list of integers and explicitly sets the data type of the elements to 8-bit integers (int8). This means that each element in the array will be stored using 8 bits, which can represent values from -128 to 127. If any value in the list exceeds this range, it will wrap around due to overflow.
print(arr)
print(arr.dtype)

In [ ]:
print(arr)
print(arr.dtype)
print(f"{arr.nbytes} bytes") # This line calculates and prints the total number of bytes consumed by the elements in the NumPy array 'arr'. The 'nbytes' attribute returns the total number of bytes used to store the array's data. Since 'arr' is an array of 5 elements with a data type of int8 (which uses 1 byte per element), the output will be '5 bytes'.

In [ ]:
arr = np.array([128, 2, 3, 4, 5], dtype=np.int8) # This line creates a NumPy array with the specified list of integers and explicitly sets the data type of the elements to 8-bit integers (int8). Since the value 128 exceeds the maximum value for int8 (127), it will wrap around due to overflow, resulting in -128 being stored in the array instead of 128.
print(arr)


# Reason for OverflowError: Python integer 128 out of bounds for int8

The error occurs because the value `128` cannot be represented in the `int8` data type.  
- `int8` can only store integers from **-128 to 127**.
- Assigning `128` to an `int8` array causes an overflow, resulting in an error or unexpected value.

**Solution:**  
Use a larger integer type, such as `int16`, to store values outside the `int8` range.
```

In [ ]:
arr = np.array([127, 2, 3, 4, 5], dtype=np.int8)
print(arr)

In [ ]:
arr = np.array([128, 2, 3, 4, 5], dtype=np.int16)
print(arr)
print(arr.dtype)
print(f"{arr.nbytes} bytes")

In [ ]:
arr = np.array([128, 200, 300, 400, 500], dtype=np.int16)
print(arr)
print(arr.dtype)
print(f"{arr.nbytes} bytes")

In [ ]:
array =np.array([1.2,3.4,5.6,7.8,9.0])
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")

In [ ]:
array =np.array([1.2,3.4,5.6,7.8,9.0], dtype=np.float16) # This line creates a NumPy array with the specified list of floating-point numbers and explicitly sets the data type of the elements to 16-bit floating-point (float16). This means that each element in the array will be stored using 16 bits, which can represent a smaller range of values with less precision compared to the default 64-bit floating-point (float64). The output will show the array with float16 precision, and the data type will be 'float16'.
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")

In [ ]:
arr = np.array([128, 200, 300, 400, 500], dtype=np.float16)
print(arr)
print(arr.dtype)
print(f"{arr.nbytes} bytes")

In [ ]:
arr = np.array([128, 200, 300, 400, 500], dtype=np.str_) # This line creates a NumPy array with the specified list of integers and explicitly sets the data type of the elements to string (str_). Each integer will be converted to its string representation, resulting in an array of strings. The output will show the array with string values, and the data type will be 'str_'.
print(arr)
print(arr.dtype)
print(f"{arr.nbytes} bytes")

In [ ]:
arr = np.array([128, 2010, 300, 400, 500], dtype=np.str_)
print(arr)
print(arr.dtype) 
print(f"{arr.nbytes} bytes")



- **Values:** `['128' '2010' '300' '400' '500']`
- **Data type:** `<U4` (Unicode string of length 4)
- **Memory usage:** Each string element uses 16 bytes (4 characters × 4 bytes per Unicode character), so the total size is `arr.nbytes` bytes.

Using `dtype=np.str_` converts all elements to strings, which is useful for storing non-numeric data or mixed types in a single array.


In [ ]:
array= np.array(["code io","lanch pad","Giridharan"]) # This line creates a NumPy array with the specified list of strings. Each string in the list will be an element in the array. The output will show the array containing the strings "code io", "lanch pad", and "Giridharan", and the data type will be 'str_'.
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")

In [ ]:
array= np.array(["code io","lanch pad","Giridharan"], dtype="<U5") # This line creates a NumPy array with the specified list of strings and explicitly sets the data type to Unicode strings with a maximum length of 5 characters (dtype="<U5"). This means that each string in the array will be truncated to 5 characters if it exceeds that length. The output will show the array with truncated string values, and the data type will be 'str_' with a maximum length of 5.
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")

In [ ]:
array= np.array([1,2,True,"lanch pad","Giridharan"]) # This line creates a NumPy array with a mixed list of elements, including integers, a boolean value, and strings. NumPy will upcast the data type to accommodate all types of elements, resulting in an array of strings (dtype='<U11') where each element is converted to its string representation. The output will show the array with string values, and the data type will be 'str_' with a maximum length of 11 characters.
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")

In [ ]:
array= np.array([1,2,True,"lanch pad","Giridharan"],dtype=np.object_) # most not use object 
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")

In [ ]:
array= np.array([True,False,True,True], dtype=np.bool_) # This line creates a NumPy array with the specified list of boolean values and explicitly sets the data type to boolean (bool_). Each element in the array will be stored as a boolean value (True or False). The output will show the array with boolean values, and the data type will be 'bool_'.
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")

In [ ]:
array =np.array([1, 2, 3, 4, 5])
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")

In [ ]:
array=array.astype(np.float16) # This line converts the data type of the elements in the NumPy array 'array' to 16-bit floating-point (float16) using the 'astype' method. This means that each element in the array will be stored using 16 bits, which can represent a smaller range of values with less precision compared to the default 64-bit floating-point (float64). The output will show the array with float16 precision, and the data type will be 'float16'.
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")

In [ ]:
array=array.astype(np.bool_) # This line converts the data type of the elements in the NumPy array 'array' to boolean (bool_) using the 'astype' method. This means that each element in the array will be evaluated for its truthiness, where non-zero values will be converted to True and zero values will be converted to False. The output will show the array with boolean values, and the data type will be 'bool_'.
print(array)
print(array.dtype)
print(f"{array.nbytes} bytes")